/* Somnia — Slovenščina */
window.LANG_SL = {
    // Splošni gumbi
    'btn.expandAll':    'Razširi vse',
    'btn.collapseAll':  'Skrni vse',
    'btn.save':         'Shrani',
    'btn.cancel':       'Prekliči',
    'btn.clear':        'Počisti',
    'btn.export':       'Izvozi',
    'btn.csv':          'CSV',
    'btn.json':         'JSON',
    'btn.delete':       'Izbriši',
    'btn.edit':         'Uredi',
    'btn.newRow':       '+ Nova vrstica',
    'btn.run':          'Zaženi',
        'btn.help':   '📖 Pomoč',
    'btn.print':        '🖨 Natisni',
    'btn.markdown':     '📝 Markdown',
    'btn.exportLabel':  'Izvozi:',
    'btn.openSqlite':   'Odpri SQLite',
    'btn.saveSqlite':   'Shrani .sqlite',
    'btn.saveDream':    '💾 Shrani sanje',
    'btn.saveSql':      '💾 Shrani',
    'btn.sqlHelp':      '📖 Pomoč',

    // Placeholderji
    'ph.search':        'Išči...',
    'ph.searchDreams':  'Išči po naslovu, vsebini...',
    'ph.searchGlobal':  'Globalno iskanje...',
    'ph.searchSaved':   'Išči poizvedbe...',
    'ph.sqlEditor':     'SELECT * FROM Dreams LIMIT 10',
    'ph.cycleActivity': 'Aktivnosti v ciklu...',

    // Sporočila
    'msg.noResults':        'Ni rezultatov',
    'msg.noData':           'Ni podatkov',
    'msg.executed':         '✓ Izvedeno uspešno',
    'msg.noDb':             'Ni odprte baze',
    'msg.noDbDesc':         'Klikni »Odpri SQLite« zgoraj in izberi .sqlite datoteko.',
    'msg.noDbShortcuts':    'Bližnjice:',
    'msg.shortcutSearch':   'iskanje',
    'msg.shortcutPages':    'strani',
    'msg.globalNoResults':  'Ni rezultatov za',

    // Toasti
    'toast.exported':       (n) => `Izvoženo ${n} vrstic`,
    'toast.exportedRec':    (n) => `Izvoženo ${n} zapisov`,
    'toast.dbOpened':       (name) => `Baza odprta: ${name}`,
    'toast.dbSaved':        (name) => `Baza shranjena: ${name}`,
    'toast.rowAdded':       'Vrstica dodana',
    'toast.rowSaved':       'Shranjeno',
    'toast.rowDeleted':     'Vrstica izbrisana',
    'toast.noPK':           'Ni PKja — brisanje ni mogoče',
    'toast.noFields':       'Ni polj za vnos',
    'toast.noUpdateFields': 'Ni polj za posodobitev',
    'toast.rowMissing':     'Napaka: vrstica ne obstaja',
    'toast.rowidMissing':   'Napaka: rowid ne najdem',
    'toast.sqlError':       (msg) => `SQL napaka: ${msg}`,
    'toast.dreamSaved':     (id) => `Sanje #${id} shranjene`,
    'toast.locCreated':     (name) => `Lokacija "${name}" ustvarjena`,
    'toast.catCreated':     (name) => `Kategorija "${name}" ustvarjena`,
    'toast.techCreated':    (name) => `Tehnika "${name}" ustvarjena`,
    'toast.suppCreated':    (name) => `Suplement "${name}" ustvarjen in dodan`,
    'toast.querySaved':     'Poizvedba shranjena',
    'toast.noQuery':        'Ni poizvedbe za shranjevanje',
    'toast.suppExists':     'Suplement je že dodan',
    'toast.dreamNotFound':  'San ne najdem',
    'toast.markdownSaved':  (name) => `Markdown izvožen: ${name}`,

    // Števniki
    'count.dreams':   (n) => n===1 ? '1 sanje' : `${n} sanj`,
    'count.cycles':   (n) => n===1 ? '1 cikel' : n<5 ? `${n} cikli` : `${n} ciklov`,
    'count.records':  (n) => n===1 ? '1 zapis' : n<5 ? `${n} zapisi` : `${n} zapisov`,
    'count.rows':     (n) => n===1 ? '1 vrstica' : n<5 ? `${n} vrstice` : `${n} vrstic`,
        'count.entries': (n) => n===1?'1 vnos':n<5?`${n} vnosi`:`${n} vnosov`,
    'count.groups':   (n) => `${n} grup`,
    'count.total':    (n, type) => {
      const s = window.LANG_SL['count.'+type];
      return s ? s(n)+' skupaj' : n+' skupaj';
    },

    // Statistike KPI
    'stats.dreams':     'sanj',
    'stats.cycles':     'spalnih ciklov',
    'stats.avgCycles':  'ciklov / san',
    'stats.activities': 'aktivnosti',
    'stats.signs':      'dream signs',
    'stats.bookmarks':  'zaznamkov',
    'stats.supps':      'suplementov',
    'stats.months':     'Sanje po mesecih',
    'stats.less':       'manj',
    'stats.more':       'več (6+)',
    'stats.total':      'skupaj',

    // Dreams tab
    'dreams.tabLabel':      '🌙 Sanje',
    'dreams.allLocs':       'Vse lokacije',
    'dreams.allCats':       'Vse kategorije',
    'dreams.bookmarks':     '★',
    'dreams.noCycles':      'Ni sleep cycle zapisov',
    'dreams.activities':    '🏃 Dnevne aktivnosti',
    'dreams.sortIdDesc':    'ID ↓',
    'dreams.sortIdAsc':     'ID ↑',
    'dreams.sortDateDesc':  'Datum ↓',
    'dreams.sortDateAsc':   'Datum ↑',
    'dreams.cyclesLabel':   (n) => n===1 ? '1 cikel' : n<5 ? `${n} cikli` : `${n} ciklov`,

    // Generic tabi — countId label
    'tab.countSuffix.activities':  'aktivnosti',
    'tab.countSuffix.perceptions': 'zapisov',
    'tab.countSuffix.dreamsigns':  'zapisov',
    'tab.countSuffix.techniques':  'zapisov',
    'tab.countSuffix.supplements': 'vnosov',

    // Ostali tabi
    'tab.activities':   '🏃 Aktivnosti',
    'tab.perceptions':  '🫧 Perception Bubbles',
    'tab.dreamsigns':   '🔮 Dream Signs',
    'tab.techniques':   '🛠️ Tehnike',
    'tab.supplements':  '💊 Suplementi',
    'tab.stats':        '📊 Statistike',
    'tab.db':           '🗄 Baza',
    'tab.newdream':     '✏️ Nova sanja',
    'tab.dbTables':     '📋 Tabele',
    'tab.dbSql':        '🔍 SQL',

    // Modal
    'modal.edit':           'Uredi',
    'modal.newRow':         'Nova vrstica',
    'modal.confirm.delete': 'Izbriši to vrstico?',

    // Global search sekcije
    'gs.dreams':      '🌙 Sanje',
    'gs.cycles':      '💤 Vsebina ciklov',
    'gs.comments':    '💬 Komentarji ciklov',
    'gs.signs':       '🔮 Dream Signs',
    'gs.percs':       '🫧 Perception Bubbles',
    'gs.activities':  '🏃 Aktivnosti',
    'gs.supps':       '💊 Suplementi',
    'gs.techniques':  '🛠️ Tehnike',
    'gs.locations':   '📍 Lokacije',
    'gs.showAll':     (n) => `Pokaži vse (${n})`,
    'gs.hide':        'Skrij',

    // SQL
    'sql.help.title':   'SQL Pomoč',
    'sql.help.saved':   'Shranjene poizvedbe',
    'sql.help.tip':     '💡 Klikni na ime tabele ali poizvedbo da jo vstaviš v editor. Ctrl+Enter za zagon.',
    'sql.noSaved':      'Ni shranjenih poizvedb',
    'sql.noSavedSearch':'Ni zadetkov',
    'sql.namePrompt':   (preview) => `Ime poizvedbe:\n${preview}`,
    'sql.saved.header': 'Shranjene',
    'sql.close':        '× Zapri',

    // Misc
    'misc.bookmark':    '★ zaznamek',
    'misc.unsaved':     'Imaš neshranjene spremembe. Zapri vseeno?',
    'misc.tables':      'Tabele',
    // Toast sporočila
    'toast.exported':     'izvoženo',
    'toast.rowAdded':     'Vrstica dodana',
    'toast.saved':        'Shranjeno',
    'toast.rowDeleted':   'Vrstica izbrisana',
    'toast.dbOpened':     'Baza odprta',
    'toast.dbSaved':      'Baza shranjena',
    'toast.dreamNotFound':'San ne najdem',
    'toast.markdownExported':'Markdown izvožen',
    'toast.noPK':         'Ni PKja — brisanje ni mogoče',
    'toast.dreamSaved':   'Sanje shranjene',
    'toast.created':      (name) => `"${name}" ustvarjeno`,

    // SQL
    'sql.noQuery':        'Ni poizvedbe za shranjevanje',
    'sql.querySaved':     'Poizvedba shranjena',
    'sql.noMatches':      'Ni zadetkov',
    'sql.noSaved':        'Ni shranjenih poizvedb',

    // Misc
    'misc.total':         'skupaj',
    'misc.of':            'od',
    'msg.noResultsFor':   'Ni rezultatov za',
    'btn.showAll':        'Pokaži vse',
    'btn.hide':           'Skrij',

    'nf.saveDream':  '💾 Shrani sanje',
    'misc.bookmark': '★ zaznamek',

    'header.openDb':  'Odpri SQLite',
    'header.saveDb':  'Shrani .sqlite',
    'db.tables':          'Tabele',
    'db.sql':             'SQL',
    'sql.helpTitle':      'SQL Pomoč',
    'sql.savedTitle':     'Shranjene poizvedbe',
    'stats.dreamsTotal':  'Skupaj sanj',
    'stats.cyclesPerDream':'Ciklov / san',
    'stats.dreamSigns':   'Dream Signs',
    'stats.supplements':  'Suplementi',
    'gs.dreamSigns':      '🔮 Dream Signs',
    'gs.perceptions':     '🫧 Perception Bubbles',
    'gs.supplements':     '💊 Suplementi',
    'misc.noDb':          'Ni odprte baze',
    'nf.titleRequired':   'Naslov je obvezen',
    'nf.addCycle':        'Dodaj vsaj en sleep cikel',
    'nf.noFields':        'Tabela nima polj za vnos',
    'card.activities':    'Aktivnosti',
    'card.exportPrint':   '🖨 Natisni',
    'card.exportMd':      '📝 Markdown',
    'card.noTitle':       '(brez naslova)',
    'card.openDream':     'Odpri v Dream View',
    'md.date':            '**Datum:**',
    'md.location':        '**Lokacija:**',
    'md.bookmark':        '**Zaznamek:** ★',
    'md.dailyActs':       '## Dnevne aktivnosti',
    'md.activities':      'Aktivnosti',
    'md.noDate':          'brez-datuma',
    'nf.addCycleBtn':     '+ Dodaj cikel',
    'nf.removeCycle':     'Odstrani cikel',
    'nf.newLocation':     'Nova lokacija',
    'nf.locationName':    'Ime nove lokacije...',
    'nf.searchLocation':  'Išči lokacijo...',
    'nf.contents':        'Vsebina',
    'nf.contentsPh':      'Vsebina sanje...',
    'nf.comments':        'Komentarji',
    'nf.commentsPh':      'Komentarji, opombe...',
    'nf.cycleActs':       'Aktivnosti (SleepCycle)',
    'nf.cycleActsPh':     'Aktivnosti v ciklu...',
    'nf.dupTitle':        'Podvojen datum',
    'nf.dupMsg':          (n, titles, date) => `Za datum ${date} že obstaja ${n} san${n===1?'':'i'}: ${titles}. Nadaljuješ?`,
    'misc.noDbDesc': 'Klikni »Odpri SQLite« zgoraj in izberi .sqlite datoteko.',
    'tab.stats_label':    'Statistike',
    'tab.db_label':       'Baza',
    'tab.newdream_label': 'Nova sanja',
    'tb.allColumns':      'Vse kolumne',
    'card.supplements':   'Suplementi',
    'stats.dreamsByMonth':'Sanje po mesecih',
    'nf.titlePh':         'Naslov sanje...',
    'nf.searchCat':       'Išči kategorijo...',
    'nf.searchTech':      'Išči tehniko...',
    'nf.searchSign':      'Išči dream sign...',
    'nf.searchPerc':      'Išči perception bubble...',
    'nf.searchSupp':      'Išči suplement...',
    'stats.topCategories': 'Najpogostejše kategorije',
    'stats.locations':     'Lokacije',
    'stats.techniques':    'Tehnike',
    'stats.actTypes':      'Tipi aktivnosti',
    'tb.actions':          'Akcije',
    'tb.page':             'stran',
    'btn.all':             'Vse',
    'btn.reset':           'Ponastavi',
    'nf.sectionDreams':    'Sanje',
    'nf.sleepCycles':      'Sleep Cikli',
    'nf.date':             'Datum',
    'nf.time':             'Čas',
    'nf.categories':       'Kategorije',
    'nf.newCategory':      'Nova kategorija',
    'nf.techniques':       'Tehnike',
    'nf.newTechnique':     'Nova tehnika',
    'nf.shortName':        'Kratko ime...',
    'nf.fullNameOpt':      'Polno ime (neobvezno)',
    'nf.dreamSigns':       'Dream Signs',
    'nf.newDreamSign':     'Nov dream sign',
    'nf.supplements':      'Suplementi',
    'nf.newSupplement':    'Nov suplement',
    'nf.perceptions':      'Perception Bubbles',
    'nf.newPerception':    'Nov perception bubble',
    'nf.descOpt':          'Opis (neobvezno)',
    'nf.dose':             'Doza',
    'nf.unit':             'Enota (npr. mg)',
    'nf.suppType':         'Tip suplementa',
    'nf.namePh':           'Ime...',
    'nf.create':           'Ustvari',
    'ph.searchActivities':   'Išči aktivnosti...',
    'ph.searchPerceptions':  'Išči perception bubbles...',
    'ph.searchDreamSigns':   'Išči dream signs...',
    'ph.searchTechniques':   'Išči tehnike...',
    'ph.searchSupplements':  'Išči suplementne zapise...',
    'sql.h.tables':         'Tabele v bazi',
    'sql.h.dreamOverview':  'Pregled sanj',
    'sql.h.sleepCycles':    'Sleep Cycles',
    'sql.h.catsTechs':      'Kategorije & Tehnike',
    'sql.h.supplements':    'Suplementi',
    'sql.h.signsPercs':     'Dream Signs & Perception Bubbles',
    'sql.h.advanced':       'Napredne poizvedbe',
    'sql.hint':             '💡 Klikni na ime tabele ali poizvedbo da jo vstaviš v editor. Ctrl+Enter za zagon.',
    'sql.q.last20':         'Zadnjih 20 sanj',
    'sql.q.byYear':         'Število sanj po letih',
    'sql.q.byMonth':        'Število sanj po mesecih',
    'sql.q.searchTitle':    'Iskanje po naslovu (zamenjaj letenje)',
    'sql.q.withLocation':   'Sanje z lokacijo',
    'sql.q.bookmarked':     'Zaznamovani cikli',
    'sql.q.searchContent':  'Iskanje po vsebini (zamenjaj vzorec)',
    'sql.q.mostCycles':     'Sanje z največ cikli',
    'sql.q.topCats':        'Najpogostejše kategorije',
    'sql.q.topTechs':       'Najpogostejše tehnike',
    'sql.q.lucid':          'Vse lucidne sanje (zamenjaj LS)',
    'sql.q.topSupps':       'Najpogosteje jemani suplementi',
    'sql.q.suppByName':     'Sanje po suplementu (zamenjaj melatonin)',
    'sql.q.topSigns':       'Najpogostejši dream signs',
    'sql.q.topPercs':       'Najpogostejši perception bubbles',
    'sql.q.lucidByYear':    'Lucidne sanje po letih',
    'sql.q.allCats':        'Sanje z vsemi kategorijami',
    'sql.q.suppLucid':      'Suplementi pri lucidnih sanjah',
    'sql.q.correlation':    'Korelacija tehnik in lucidnosti',
        'misc.shortcuts': 'Bližnjice: / iskanje · ←→ strani · N nova sanja',
        'btn.close':  'Zapri',
    'setup.title':              'dream/db setup',
    'setup.subtitle':           'Pripravi svojo bazo za Somnia',
    'setup.newDb.title':        'Nova baza',
    'setup.newDb.desc':         'Ustvari svežo SQLite bazo z vsemi tabelami. Primerno za nov dnevnik ali deljenje z drugimi.',
    'setup.newDb.btn':          'Ustvari in prenesi',
    'setup.newDb.stepLabel':    'Ustvari novo prazno bazo',
    'setup.newDb.stepSmall':    'Vse tabele s PKji in FKji, brez podatkov',
    'setup.existing.label':     'Odpri obstoječo bazo',
    'setup.existing.small':     'Naloži .sqlite datoteko in jo nastavi spodaj',
    'setup.existing.btn':       'Izberi bazo…',
    'setup.demo.title':         'Demo podatki',
    'setup.demo.btn':           'Izberi bazo…',
    'setup.demo.stepLabel':     'Uvozi demo podatke v obstoječo bazo',
    'setup.demo.stepSmall':     'Odpri .sqlite datoteko in izberi kaj uvoziti',
    'setup.pin.title':          'PIN zaščita',
    'setup.pin.desc':           'Nastavi 4-mestni PIN ki se zahteva ob odprtju browserja.',
    'setup.pin.set':            'Nastavi PIN',
    'setup.pin.change':         'Spremeni PIN',
    'setup.pin.remove':         'Odstrani PIN',
    'setup.pin.isSet':          'PIN je nastavljen',
    'setup.pin.notSet':         'PIN trenutno ni nastavljen',
    'setup.pin.stepLabel':      'Nastavi ali posodobi PIN',
    'setup.pin.recoveryHint':   'Recovery koda — zapiši si jo:',
    'setup.pin.recoveryOnce':   'Koda je vidna samo enkrat. Shrani jo na varno.',
    'setup.forgot.title':       'Pozabljeni PIN',
    'setup.forgot.desc':        'Če si pozabil PIN, vnesi recovery kodo ki si jo dobil ob nastavitvi.',
    'setup.forgot.btn':         'Ponastavi PIN',
    'setup.forgot.placeholder': 'XXXX-XXXX-XXXX-XXXX',
        'setup.optional':       'Opcijsko',
        'setup.step1.title':    'Nova baza',
        'setup.step1.desc':     'Ustvari svežo SQLite bazo z vsemi tabelami. Primerno za nov dnevnik ali deljenje z drugimi.',
        'setup.step1.btn':      'Ustvari in prenesi',
        'setup.step1b.desc':    'Odpri obstoječo bazo za pin/demo nastavitve',
        'setup.step1b.sub':     'Naloži .sqlite datoteko in jo nastavi spodaj',
        'setup.step1b.btn':     'Izberi bazo…',
        'setup.step2.title':    'Demo podatki',
        'setup.step2.desc':     'Uvozi predpripravljene šifrante: kategorije, tehnike, suplementi, dream signs, perception bubbles.',
        'setup.step2.btn':      'Izberi bazo…',
        'setup.step3.title':    'PIN zaščita',
        'setup.step3.desc':     'Nastavi 4-mestni PIN ki se zahteva ob odprtju browserja.',
        'setup.recovery.title': 'Pozabljeni PIN',
        'setup.recovery.desc':  'Vnesi recovery kodo ki si jo dobil ob nastavitvi. PIN bo izbrisan.',
        'setup.recovery.btn':   'Ponastavi PIN',
        'setup.recovery.ph':    'XXXX-XXXX-XXXX-XXXX',
        'setup.step1a':         'Ustvari novo prazno bazo',
        'setup.step1a.sub':     'Vse tabele s PKji in FKji, brez podatkov',
        'setup.step2a':         'Uvozi demo podatke v obstoječo bazo',
        'setup.step2a.sub':     'Najprej odpri bazo (korak 1b) ali izberi tukaj',
        'setup.pin.active':     'PIN je nastavljen ✓',
        'setup.recovery.save':  'Recovery koda — zapiši si jo:',
        'setup.recovery.once':  'Koda je vidna samo enkrat. Shrani jo na varno.',
        'setup.demo.desc':      'Izberi katere podatke želiš uvoziti:',
        'setup.import':         'Uvozi izbrano',
        'wiz.next':   'Naprej',
        'wiz.back':   'Nazaj',
        'wiz.finish': 'Začni',
        'wiz.skip':   'Preskoči uvod',
        'wiz.step1.title': 'Dobrodošel v Somnia',
        'wiz.step1.desc':  'Lokalni browser za tvoj SQLite sanjski dnevnik. Vsi podatki ostanejo pri tebi.',
        'wiz.step2.title': 'Odpri svojo bazo',
        'wiz.step2.desc':  'Klikni <strong>Odpri SQLite</strong> v zgornjem desnem kotu in izberi svojo <code>.sqlite</code> datoteko.<br><br>Nimaš baze? Ustvari jo v <a href="setup.html" style="color:var(--accent2)">setup.html</a>.',
        'wiz.step3.title': 'Navigacija',
        'wiz.step3.desc':  'Tabi zgoraj: 🌙 Sanje, 🛠️ Tehnike, 🔮 Dream Signs, 💊 Suplementi, 🫧 Perception Bubbles, 🏃 Aktivnosti, 📊 Statistike, 🗄 Baza, ✏️ Nova sanja.<br><br>Bližnjice: <kbd style="font-family:monospace;background:var(--bg3);padding:1px 5px;border-radius:3px">/</kbd> iskanje &nbsp; <kbd style="font-family:monospace;background:var(--bg3);padding:1px 5px;border-radius:3px">N</kbd> nova sanja',
        'wiz.step4.title': 'Shranjevanje',
        'wiz.step4.desc':  'Klikni <strong>Shrani .sqlite</strong> po vsaki seji. Utripajoča pika opozori na neshranjene spremembe.<br><br>Gumb ❓ v headerju odpre pomoč kadarkoli.',
        'help.tabs':           'Tabi',
        'help.shortcuts':      'Bližnjice',
        'help.tips':           'Nasveti',
        'help.setup':          'Za ustvarjanje novih baz, uvoz demo podatkov in PIN zaščito odpri',
        'help.tab.dreams':     'Accordion prikaz vseh sanj z vsemi podrobnostmi, filtri po lokaciji in kategoriji, iskanje z označevanjem',
        'help.tab.techniques': 'Technike lucidnega sanjanja (MILD, WILD, SSILD...) grupirane po imenu',
        'help.tab.dreamsigns': 'Ponavljajoči simboli v sanjah grupirani po imenu',
        'help.tab.supplements':'Suplementi grupirani po preparatu z dozami',
        'help.tab.perceptions':'Zaznavni motivi grupirani po imenu',
        'help.tab.activities': 'Dnevne aktivnosti grupirane po tipu',
        'help.tab.stats':      'KPI kartice, frekvenčni grafikoni, heatmap po mesecih in letih',
        'help.tab.db':         'Table browser za direktno urejanje podatkov + SQL editor za poljubne poizvedbe',
        'help.tab.newdream':   'Obrazec za vnos nove sanje z vsemi podrobnostmi (cikli, kategorije, tehnike, suplementi...)',
        'help.sc.search':      'Fokus na iskalnik aktivnega taba',
        'help.sc.newdream':    'Odpri Nova sanja',
        'help.sc.pages':       'Prejšnja / naslednja stran',
        'help.sc.sql':         'Zaženi SQL poizvedbo (v Baza → SQL)',
        'help.sc.close':       'Zapri modal / iskalnik / pomoč',
        'help.tip1':           '💡 Globalno iskanje v headerju išče po vseh virih hkrati',
        'help.tip2':           '🖨 Vsako sanje lahko natisneš ali izvoziš kot Markdown (sticky bar v razviti kartici)',
        'help.tip3':           '💾 SQL poizvedbe shrani z gumbom Shrani v SQL editorju — dostopne so v Pomoč overlayju',
        'help.tip4':           '🔒 PIN zaščito nastavi v setup.html',
        'toast.actAdded':      'Aktivnost dodana',
        'toast.addCycle':      'Dodaj vsaj en sleep cikel',
        'toast.titleRequired': 'Naslov je obvezen',
        'toast.dreamIdErr':    'Napaka: DreamID ni bil ustvarjen',
        'toast.noTableFields': 'Tabela nima polj za vnos',
        'toast.alreadyAdded':  'Že dodano',
        'toast.suplAdded':     'Suplement je že dodan',
        'toast.enterSign':     'Vnesi ime dream signa',
        'toast.enterCat':      'Vnesi ime kategorije',
        'toast.enterLoc':      'Vnesi ime lokacije',
        'toast.enterPerc':     'Vnesi ime perception bubble',
        'toast.enterSupp':     'Vnesi ime suplementa',
        'toast.enterTech':     'Vnesi kratko ime tehnike',
        'toast.pinNotSet':     'PIN ni nastavljen. Nastavi ga v setup.html',
        'toast.pinReset':      'PIN ponastavljen. Nastavi novega v setup.html',
    'tab.dreams':          '🌙 Sanje',
    'help.title':          'Pomoč',
    'nf.title':            'Naslov',
    'nf.location':         'Lokacija',
    'nf.cycle':            'Cikel',
    'nf.remove':           'Odstrani',
};
